// <auto-generated />
using System;
using CourseCreator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseCreator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241106202037_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseCreator.Domain.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7c6add4-4f9c-41e2-b53e-91e6ec159291"),
                            Description = "Test Course 1",
                            Name = "Course 1"
                        },
                        new
                        {
                            Id = new Guid("a80b3b2b-3213-4e47-96ca-1471b9c1e3e4"),
                            Description = "Test Course 2",
                            Name = "Course 2"
                        },
                        new
                        {
                            Id = new Guid("c7ec3142-9764-4ebe-bc80-0d83b837e2ef"),
                            Description = "Test Course 3",
                            Name = "Course 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
